name: "coconet"

services:
  bootnode:
    hostname: bootnode
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_bootnode.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    healthcheck:
      test: curl -f localhost:8080/p2p
    ports:
      - 8545:8545
      - 8551:8551
      # - 8080:8080
      # - 8081:8081
      # - 9090:9090
    environment:
      - PUBLIC_IP=10.5.0.5
    networks:
      devnet:
        ipv4_address: 10.5.0.5

  node1:
    hostname: node1
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_node.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8546:8545
      # - 9091:9090
      # - 7501:7500
    environment:
      - PUBLIC_IP=10.5.0.6
      - HAS_VALIDATOR=1
    networks:
      devnet:
        ipv4_address: 10.5.0.6
    depends_on:
      bootnode:
        condition: service_healthy

  node2:
    hostname: node2
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_node.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8547:8545
      # - 9092:9090
    environment:
      - PUBLIC_IP=10.5.0.7
      - HAS_VALIDATOR=1
    networks:
      devnet:
        ipv4_address: 10.5.0.7
    depends_on:
      bootnode:
        condition: service_healthy

  node3:
    hostname: node3
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_node.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8548:8545
      # - 9093:9090
    environment:
      - PUBLIC_IP=10.5.0.8
    networks:
      devnet:
        ipv4_address: 10.5.0.8
    depends_on:
      bootnode:
        condition: service_healthy

networks:
  devnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1