name: "coconet"

services:
  bootnode:
    hostname: bootnode
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_bootnode.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8545:8545
    environment:
      - PUBLIC_IP=10.5.0.5
    networks:
      devnet:
        ipv4_address: 10.5.0.5

  node1:
    hostname: node1
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_node.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8546:8545
    environment:
      - PUBLIC_IP=10.5.0.6
    networks:
      devnet:
        ipv4_address: 10.5.0.6
    depends_on:
      bootnode:
        condition: service_started

  node2:
    hostname: node2
    image: eth_node
    volumes:
      - ./consensus:/devnet/consensus
      - ./execution:/devnet/execution
      - ./start_node.sh:/devnet/start.sh
    command: sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - 8547:8545
    environment:
      - PUBLIC_IP=10.5.0.7
    networks:
      devnet:
        ipv4_address: 10.5.0.7
    depends_on:
      bootnode:
        condition: service_started

networks:
  devnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1